services:
  - type: web
    name: html-protector-bot
    runtime: python
    buildCommand: pip install -r requirements.txt && npm install -g javascript-obfuscator
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
